version: "0.1"
services:
  relay:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
    ports:
      - 8001:8001
    build:
      dockerfile: backend.dockerfile
    command:
      - bash
      - -c
      - |
        set -e
        python pyrelay/relay/server.py